config/routes.rb
SamlIpd::Application.routes.draw do
  get '/saml/auth'     => 'idp#new'
  get '/saml/metadata' => 'idp#show'
  post '/saml/auth'    => 'idp#create'
  

end

app/models/user.rb
class User
  attr_accessor :email, :name

  def self.valid_user(email)
    u        = User.new
    u.email  = email
    u.name   = email.split('@').first.capitalize
    u
  end

  def valid_password?(password)
    true
  end

  ##### IMPORTANT SAML BEHAVIOR #####

  # returns the email address
  def persistent
    email
  end

  # returns a count of the number of account the user is a member of
  #
  # this can be used by an SP to show a link to allow the user to jump accounts
  def account_count
    3
  end

  # returns a hash of the currently selected account
  # MUST include
  #  uuid: a globally unique ID for the account
  #  name: the name of the account
  def selected_account
    {
        uuid: '6888dce0-43d1-0131-9c64-482a14030d65',
        name: 'Demo account'
    }.to_json.to_s
  end

  # returns an array of the modules that a user was given access to
  #
  # this is used by an SP to reject a login attempt from a user that does not
  # have access to the module
  def modules_enabled
    ['account','cms','crm','forum','university',].to_json.to_s
  end
  

  # returns of the user is the account owner: "superadmin"
  def is_account_owner
    # only waterfall-admin
    email == 'waterfall-admin@waterfallsoftware.com'
  end
  
  # return a hash of permissions
  def permissions
    # super admins do not need account access
    return {}.to_json.to_s if is_account_owner
    
    everyone = {
      'Forum' => %w(index show),
      'Topic' => %w(index show create),
      'Post'  => %w(index show create update destroy)
    }
    
    if email == 'admin@waterfallsoftware.com'
      everyone['Forum'].concat %w(create update destroy)
      everyone['Topic'].concat %w(update destroy)
    end
    
    everyone.to_json.to_s
  end
  
  def uda
    uda = {
      'key' => 'value'
    }
    uda.to_json.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/idp_controller.rb
class IdpController < SamlIdp::IdpController
  def new
    # override the gem provided form
  end

private
  def idp_authenticate(email, password) # not using params intentionally
    User.valid_user(email)
  end

  def idp_make_saml_response(found_user) # not using params intentionally
    encode_response found_user
  end
end

app/controllers/saml_idp_controller.rb
class ::SamlIdpController < SamlIdp::IdpController
private
  def idp_authenticate(email, password) # not using params intentionally
    logger.debug '-'*80
    logger.debug 'idp_authenticate'
    logger.debug email.inspect
    logger.debug password.inspect

    user = User.by_email(email).first
    user && user.valid_password?(password) ? user : nil
  end

  def idp_make_saml_response(found_user) # not using params intentionally
    logger.debug '-'*80
    logger.debug 'ipd_make_saml'
    logger.debug found_user.inspect
    
    encode_response found_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/idp/_form.html.erb
<%= form_tag saml_auth_path, :method => 'POST' do %>
  <%= hidden_field_tag("SAMLRequest", params[:SAMLRequest]) %>
  <%= hidden_field_tag("RelayState", params[:RelayState]) %>

  <%# fake a user and password %>
  <%= hidden_field_tag :email,        email %>
  <%= hidden_field_tag :password,     'password' %>

  <%= submit_tag "Login as #{email}" %>
<% end %>

app/views/idp/new.html.erb
<% if @saml_idp_fail_msg %>
  <div id="saml_idp_fail_msg" class="flash error"><%= @saml_idp_fail_msg %></div>
<% end %>

<%= render :partial => 'form', :locals => {
    :email        => 'waterfall-admin@waterfallsoftware.com'
} %>

<%= render :partial => 'form', :locals => {
    :email        => 'admin@waterfallsoftware.com'
} %>

<%= render :partial => 'form', :locals => {
    :email        => 'normal@waterfallsoftware.com'
} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SamlIpd</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>